name: simpegEM1D-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - mkl
  - discretize
  # - gcc
  - pip:
    - git+https://github.com/simpeg/simpegEM1D.git@master

